### ISSUE TITLE
Attempted import error: 'createStitches' is not exported from '@stitches/react' (imported as 'mc').

### ISSUE THREAD

**Issue by xixingya** [tldraw/tldraw#1011]
when I use <Tldraw id={'aaaaa'} currentPageId={1} /> the error is occur

"react-dom": "^17.0.2",
node -v is v16.17.1

**Comment by judicaelandria** [comment]
Hey! can you please try to reproduce it codesandbox and post it here?
in the meantime, here's how i did it, 
https://codesandbox.io/s/simple-tldraw-app-c9ixl0?file=/src/App.tsx

**Comment by xixingya** [comment]
> 

maybe it is my project problem,thank you

**Comment by xixingya** [comment]
./node_modules/@tldraw/tldraw/dist/index.mjs
Can't import the named export 'createElement' from non EcmaScript module (only default export is available)

**Comment by judicaelandria** [comment]
the best thing you can do is create a minimal reproduction in codesandbox that shows the issue

**Comment by judicaelandria** [comment]
can you please try to update your react scripts?

**Comment by xixingya** [comment]
> the best thing you can do is create a minimal reproduction in codesandbox that shows the issue

hello,I am sorry I can not reproduce this in codesandbox,I use webpack but it not works and I update the react-scripts and it is not works too

**Comment by xixingya** [comment]
{
    "@atlaskit/css-reset": "^6.0.5",
    "@babel/core": "7.12.3",
    "@pmmmwh/react-refresh-webpack-plugin": "0.4.3",
    "@svgr/webpack": "5.5.0",
    "@testing-library/jest-dom": "^5.14.1",
    "@testing-library/react": "^11.2.7",
    "@testing-library/user-event": "^12.8.3",
    "@tldraw/tldraw": "^1.25.0",
    "@typescript-eslint/eslint-plugin": "^4.5.0",
    "@typescript-eslint/parser": "^4.5.0",
    "alife-logger": "^1.8.30",
    "antd": "^4.16.6",
    "axios": "^0.21.1",
    "babel-eslint": "^10.1.0",
    "babel-jest": "^26.6.0",
    "babel-loader": "8.1.0",
    "babel-plugin-named-asset-import": "^0.3.7",
    "babel-preset-react-app": "^10.0.0",
    "bfj": "^7.0.2",
    "camelcase": "^6.1.0",
    "case-sensitive-paths-webpack-plugin": "2.3.0",
    "copy-to-clipboard": "^3.3.1",
    "cross-env": "^7.0.3",
    "css-loader": "4.3.0",
    "dotenv": "8.2.0",
    "dotenv-expand": "5.1.0",
    "eslint": "^7.11.0",
    "eslint-config-react-app": "^6.0.0",
    "eslint-plugin-flowtype": "^5.2.0",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-jest": "^24.1.0",
    "eslint-plugin-jsx-a11y": "^6.3.1",
    "eslint-plugin-react": "^7.21.5",
    "eslint-plugin-react-hooks": "^4.2.0",
    "eslint-plugin-testing-library": "^3.9.2",
    "eslint-webpack-plugin": "^2.5.2",
    "file-loader": "6.1.1",
    "fs-extra": "^9.0.1",
    "html-webpack-plugin": "4.5.0",
    "identity-obj-proxy": "3.0.0",
    "immutable": "^4.0.0-rc.14",
    "jest": "26.6.0",
    "jest-circus": "26.6.0",
    "jest-resolve": "26.6.0",
    "jest-watch-typeahead": "0.6.1",
    "mini-css-extract-plugin": "0.11.3",
    "moment": "^2.29.4",
    "optimize-css-assets-webpack-plugin": "5.0.4",
    "pnp-webpack-plugin": "1.6.4",
    "postcss-flexbugs-fixes": "4.2.1",
    "postcss-loader": "3.0.0",
    "postcss-normalize": "8.0.1",
    "postcss-preset-env": "6.7.0",
    "postcss-safe-parser": "5.0.2",
    "prompts": "2.4.0",
    "prop-types": "^15.8.1",
    "react": "^17.0.2",
    "react-app-polyfill": "^2.0.0",
    "react-app-rewired": "^2.2.1",
    "react-beautiful-dnd": "^13.1.0",
    "react-cookie": "^4.1.1",
    "react-cookies": "^0.1.1",
    "react-copy-to-clipboard": "^5.1.0",
    "react-dev-utils": "^11.0.3",
    "react-dom": "^17.0.2",
    "react-error-overlay": "^6.0.9",
    "react-ga4": "^1.4.1",
    "react-infinite-scroll-component": "^6.1.0",
    "react-redux": "^7.2.4",
    "react-refresh": "^0.8.3",
    "react-router-dom": "^6.3.0",
    "react-scripts": "4.0.2",
    "react-shepherd": "^4.1.0",
    "redux": "^4.1.1",
    "redux-immutable": "^4.0.0",
    "redux-thunk": "^2.3.0",
    "resolve": "1.18.1",
    "resolve-url-loader": "^3.1.2",
    "sass-loader": "^10.0.5",
    "semver": "7.3.2",
    "style-loader": "1.3.0",
    "styled-components": "^5.3.0",
    "terser-webpack-plugin": "4.2.3",
    "ts-pnp": "1.2.0",
    "url-loader": "4.1.1",
    "web-vitals": "^1.1.2",
    "webpack": "4.44.2",
    "webpack-dev-server": "3.11.0",
    "webpack-manifest-plugin": "2.2.0",
    "workbox-webpack-plugin": "5.1.4"
  },
"scripts": {
// this is start I change to  react-app-rewired but it is not work
    "start": "cross-env REACT_APP_ENV=dev react-app-rewired start",
    "start:local": "cross-env REACT_APP_ENV=local node scripts/start.js",
    "build": "node scripts/build.js",
    "build:prod": "cross-env REACT_APP_ENV=production node scripts/build.js",
    "build:dev": "cross-env REACT_APP_ENV=development node scripts/build.js",
    "test": "node scripts/test.js"
  },

**Comment by xixingya** [comment]
the console has follow error:
Uncaught TypeError: Object(...) is not a function
    at ./node_modules/@tldraw/tldraw/dist/index.mjs (index.mjs:71:1)
    at __webpack_require__ (bootstrap:851:1)
    at fn (bootstrap:150:1)
    at Module.<anonymous> (AppItem.js:23:1)
    at ./src/components/tinyapp/ClockAppItem.js (ClockAppItem.js:38:1)
    at __webpack_require__ (bootstrap:851:1)
    at fn (bootstrap:150:1)
    at Module.<anonymous> (ClockAppItem.js:38:1)
    at ./src/components/tinyapp/TinyApp.js (TinyApp.js:30:1)
    at __webpack_require__ (bootstrap:851:1)
    at fn (bootstrap:150:1)
    at Module.<anonymous> (TinyApp.js:30:1)
    at ./src/components/tinyapp/TinyAppContainer.js (TinyAppContainer.js:53:1)
    at __webpack_require__ (bootstrap:851:1)
    at fn (bootstrap:150:1)
    at Module.<anonymous> (MainContent.css?21cd:82:1)
    at ./src/MainContent.js (MainContent.js:448:1)
    at __webpack_require__ (bootstrap:851:1)
    at fn (bootstrap:150:1)
    at Module.<anonymous> (index.css?bb0a:82:1)
    at ./src/index.js (index.js:549:1)
    at __webpack_require__ (bootstrap:851:1)
    at fn (bootstrap:150:1)
    at 1 (method.jsx:250:1)
    at __webpack_require__ (bootstrap:851:1)
    at checkDeferredModules (bootstrap:45:1)
    at Array.webpackJsonpCallback [as push] (bootstrap:32:1)
    at main.chunk.js:1:71
./node_modules/@tldraw/tldraw/dist/index.mjs @ index.mjs:71
__webpack_require__ @ bootstrap:851
fn @ bootstrap:150
(anonymous) @ AppItem.js:23
./src/components/tinyapp/ClockAppItem.js @ ClockAppItem.js:38
__webpack_require__ @ bootstrap:851
fn @ bootstrap:150
(anonymous) @ ClockAppItem.js:38
./src/components/tinyapp/TinyApp.js @ TinyApp.js:30
__webpack_require__ @ bootstrap:851
fn @ bootstrap:150
(anonymous) @ TinyApp.js:30
./src/components/tinyapp/TinyAppContainer.js @ TinyAppContainer.js:53
__webpack_require__ @ bootstrap:851
fn @ bootstrap:150
(anonymous) @ MainContent.css?21cd:82
./src/MainContent.js @ MainContent.js:448
__webpack_require__ @ bootstrap:851
fn @ bootstrap:150
(anonymous) @ index.css?bb0a:82
./src/index.js @ index.js:549
__webpack_require__ @ bootstrap:851
fn @ bootstrap:150
1 @ method.jsx:250
__webpack_require__ @ bootstrap:851
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1
index.js:1273 ./node_modules/@tldraw/tldraw/dist/index.mjs
Attempted import error: 'createStitches' is not exported from '@stitches/react' (imported as 'mc').
console.<computed> @ index.js:1273
handleErrors @ webpackHotDevClient.js:149
push../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:188
index.js:1273 ./node_modules/@tldraw/tldraw/dist/index.mjs
Attempted import error: 'defaultThemeMap' is not exported from '@stitches/react' (imported as 'gc').
console.<computed> @ index.js:1273
handleErrors @ webpackHotDevClient.js:149
push../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:188
index.js:1273 ./node_modules/@tldraw/tldraw/dist/index.mjs
Attempted import error: 'get' is not exported from 'idb-keyval' (imported as 'UW').
console.<computed> @ index.js:1273
handleErrors @ webpackHotDevClient.js:149
push../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:188
2index.js:1273 ./node_modules/@tldraw/tldraw/dist/index.mjs
Attempted import error: 'get' is not exported from 'idb-keyval' (imported as 'no').
console.<computed> @ index.js:1273
handleErrors @ webpackHotDevClient.js:149
push../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:188
