### ISSUE TITLE
React re-render exception on Vite HMR

### ISSUE THREAD

**Issue by tomlikestorock** [tldraw/tldraw#1989]
### What happened?

In a project that uses vite and tldraw-canary and a custom shape implementation, any saving of a file in the project will cause react to throw a "too many re-renders" exception... on every _other_ save.

Some light research points me towards the store events on load going crazy. Maybe something with failing to load from indexdb?

This blows up if you recreate the Custom Config example in a separate repo, but if you attempt this on the Custom Config example in the main tldraw repo itself, the whole tldraw page just reloads and does not persist your work leaving you with an empty page. This is true with the Only Editor example as well, since it uses a custom shape.

### How can we reproduce the bug?

1. Clone my repo https://github.com/tomlikestorock/tldrawHMRExceptionRepro
2. cd tldrawRepro
3. npm install && npm run dev
4. Open browser to empty board
5. With App.tsx open, save it, vite hmr reload should occur
6. Witness exception shown in browser
7. With App.tsx open, save it, vite hmr reload should occur
8. Witness board shown again in initial state
9. Repeat step 5 to loop

### What browsers are you seeing the problem on?

Firefox, Chrome

### Contact Details

tomlikestorock@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by codinglabs** [comment]
I have run into a similar bug that I assume is related. I follow the same example but in a next.js 14 repo with a custom shape like the Custom Config example. This happens if I isolate the editor and don't pass the custom shape util + remove handleMount event. Oddly I had it running before and even going back a couple commits  in my repo (where I verified that it worked before with a custom shape) doesn't help anymore.

```
Uncaught Error: Too many re-renders. React limits the number of renders to prevent an infinite loop.
    at renderWithHooks (react-dom.development.js:16317:1)
    at updateFunctionComponent (react-dom.development.js:19588:1)
    at beginWork (react-dom.development.js:21601:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)
    at renderRootSync (react-dom.development.js:26434:1)
    at recoverFromConcurrentError (react-dom.development.js:25850:1)
    at performConcurrentWorkOnRoot (react-dom.development.js:25750:1)
    at workLoop (scheduler.development.js:266:1)
    at flushWork (scheduler.development.js:239:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:533:1)

The above error occurred in the <TldrawEditorWithOwnStore> component:
    at TldrawEditorWithOwnStore (webpack-internal:///./node_modules/@tldraw/editor/dist-esm/lib/TldrawEditor.mjs:101:11)
    at EditorComponentsProvider (webpack-internal:///./node_modules/@tldraw/editor/dist-esm/lib/hooks/useEditorComponents.mjs:47:37)
    at ContainerProvider (webpack-internal:///./node_modules/@tldraw/editor/dist-esm/lib/hooks/useContainer.mjs:14:3)
    at ErrorBoundary (webpack-internal:///./node_modules/@tldraw/editor/dist-esm/lib/components/ErrorBoundary.mjs:11:1)
    at OptionalErrorBoundary (webpack-internal:///./node_modules/@tldraw/editor/dist-esm/lib/components/ErrorBoundary.mjs:29:3)
    at div
    at TldrawEditor2 (webpack-internal:///./node_modules/@tldraw/editor/dist-esm/lib/TldrawEditor.mjs:56:3)
    at Canvas (webpack-internal:///./src/_components/App/Canvas/Canvas.tsx:29:9)
    at div
    at Window (webpack-internal:///./src/_components/App/Window.tsx:24:20)
    at div
    at ThemeProvider (webpack-internal:///./node_modules/theming/dist/theming.esm.js:87:37)
    at div
    at Page (webpack-internal:///./src/App.tsx:29:92)
    at LoadableComponent (webpack-internal:///./node_modules/next/dist/shared/lib/loadable.shared-runtime.js:113:9)
    at Home
    at App (webpack-internal:///./node_modules/next/dist/pages/_app.js:24:1)
    at PathnameContextProviderAdapter (webpack-internal:///./node_modules/next/dist/shared/lib/router/adapters.js:79:11)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:2:5391)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:2:7787)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:79:1)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:183:11)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:397:11)
```

The component rendering the custom shape

```typescript
const useCanvasStyles = createUseStyles({
    editor: {
        height: "100%",
        width: "100%",
    }
})


const Canvas: React.FC<CanvasProps> = ({  }) => {
    const tools = []
    const shapes = [MyCustomShape]

    const styles = useCanvasStyles()

    const handleMount = (editor: Editor) => {
        editor
            .selectAll()
            .deleteShapes(editor.selectedShapeIds)
		    .createShapes([
			{
				id: createShapeId(),
				type: 'metaShape',
				x: 128 + Math.random() * 500,
				y: 128 + Math.random() * 500,
				props: {
					w: 200,
					h: 100,
					customObject: {},
                                        customProp: "card"
				},
			},
		])

    }

    return (
        <TldrawEditor 
            className={styles.editor}
            shapeUtils={shapes}
            onMount={handleMount}
        />
    )
};

export default Canvas;
```

The custom shape
```typescript

export class MyCustomShape extends ShapeUtil<IMyCustomShape > {
	static override type = 'metaShape' as const
	// A validation schema for the shape's props (optional)
	static override props = recordSetShapeProps
	// Migrations for upgrading shapes (optional)
	// static override migrations = cardShapeMigrations

	// Flags
	override isAspectRatioLocked = (_shape: IMyCustomShape) => false
	override canResize = (_shape: IMyCustomShape) => true
	override canBind = (_shape: IMyCustomShape) => false

	getDefaultProps(): IMyCustomShape['props'] {
		return {
			w: 300,
			h: 300,
			customObject: {},
			customProp: "card"
		}
	}

	getGeometry(shape: IMyCustomShape) {
		return new Rectangle2d({
			width: shape.props.w,
			height: shape.props.h,
			isFilled: true,
		})
	}

	// Render method — the React component that will be rendered for the shape
	component(shape: IMyCustomShape) {
		const bounds = this.editor.getShapeGeometry(shape).bounds
		const theme = getDefaultColorTheme({ isDarkMode: this.editor.user.isDarkMode })

		// Unfortunately eslint will think this is a class components
		// eslint-disable-next-line react-hooks/rules-of-hooks
		const [count, setCount] = useState(0)

		return (
			<HTMLContainer
				id={shape.id}
				style={{
					border: '1px solid black',
					display: 'flex',
					flexDirection: 'column',
					alignItems: 'center',
					justifyContent: 'center',
					pointerEvents: 'all',
				}}
			>
				<h2>Clicks: {count}</h2>
				<button
					onClick={() => setCount((count) => count + 1)}
					// You need to stop the pointer down event on buttons
					// that should prevent shape selection or click and drag
					onPointerDown={(e) => e.stopPropagation()}
				>
					{bounds.w.toFixed()}x{bounds.h.toFixed()}
				</button>
			</HTMLContainer>
		)
	}

	// Indicator — used when hovering over a shape or when it's selected; must return only SVG elements here
	indicator(shape: IRecordSetShape) {
		return <rect width={shape.props.w} height={shape.props.h} />
	}

	// Events
	override onResize: TLOnResizeHandler<IRecordSetShape> = (shape, info) => {
		return resizeBox(shape, info)
	}
}


```

**Comment by ducan-ne** [comment]
I have run into similar issue too, it doesn't happens if I didn't pass any custom shape

**Comment by OriginalEXE** [comment]
Can reproduce the same in remix + Vite setup.

I've noticed that if I wrap my `customShapeUtils` which is an array of `shapeUtils` into `useRef`, then the issue goes away, but obviously the new changes are not applied to shapes until I hard-reload.

**Comment by OriginalEXE** [comment]
Ok, I was able to arrive at a solution that works for me with no apparent downsides (so far), with Vite HMR (I'm using it within Remix, but I imagine that detail is unimportant):

1. Make sure you pass your own store to Tldraw:
```
const [store] = useState(() => {
  const newStore = createTLStore({
    shapeUtils: [...customShapeUtils, ...defaultShapeUtils],
  });

  return newStore;
});

return <Tldraw
  store={store}
  shapeUtils={[...customShapeUtils, ...defaultShapeUtils]}
  // ...
>
```

2. Create a new component which will server as a "reloader":
```
import { TLAnyShapeUtilConstructor, useEditor } from "@tldraw/tldraw";
import { useEffect } from "react";

const CanvasDevReloader = ({
  customShapes,
}: {
  customShapes: TLAnyShapeUtilConstructor[];
}) => {
  const editor = useEditor();

  useEffect(() => {
    for (const shape of editor.renderingShapes) {
      editor.shapeUtils = {
        ...editor.shapeUtils,
      };

      editor.deleteShape(shape.id);
      editor.createShape(shape.shape);
    }
  }, [customShapes]);

  return null;
};

export default CanvasDevReloader;
```
and then include it nested within `<Tldraw>`:
```
<Tldraw
  store={store}
  shapeUtils={[...customShapeUtils, ...defaultShapeUtils]}
  // ...
>
  <CanvasDevReloader customShapes={customShapeUtils} />
</Tldraw>
```

Within this setup everything seems to be working fine. I haven't gotten into the nitty-gritty with Tldraw so I imagine some functionality might break on HMR, but for now at least everything seems to be working well 🤞🏻

**Comment by OriginalEXE** [comment]
It works, thank you!

I have noticed that changes to shapes `component` don't trigger the re-render, so I'll still need a version of my "dev reloader" component to recreate the shapes, but no other ugly hacks needed any more, thanks :)
