### ISSUE TITLE
TypeError findLast is not a function

### ISSUE THREAD

**Issue by chr15m** [tldraw/tldraw#2031]
### What happened?

```
TypeError: r.findLast is not a function
    at https://www.tldraw.com/_next/static/chunks/pages/_app-9edcb256d77d153e.js:18:273878
    at Array.map (<anonymous>)
    at Object.do (https://www.tldraw.com/_next/static/chunks/pages/_app-9edcb256d77d153e.js:18:273726)
    at https://www.tldraw.com/_next/static/chunks/pages/_app-9edcb256d77d153e.js:18:227145
    at https://www.tldraw.com/_next/static/chunks/pages/_app-9edcb256d77d153e.js:18:228065
    at C (https://www.tldraw.com/_next/static/chunks/pages/_app-9edcb256d77d153e.js:18:47568)
    at e.ignoringUpdates (https://www.tldraw.com/_next/static/chunks/pages/_app-9edcb256d77d153e.js:18:228046)
    at n.i [as _createShapes] (https://www.tldraw.com/_next/static/chunks/pages/_app-9edcb256d77d153e.js:18:227104)
    at n.r.createShapes (https://www.tldraw.com/_next/static/chunks/pages/_app-9edcb256d77d153e.js:18:337721)
    at https://www.tldraw.com/_next/static/chunks/pages/_app-9edcb256d77d153e.js:18:513340
    at https://www.tldraw.com/_next/static/chunks/pages/_app-9edcb256d77d153e.js:18:227755
    at https://www.tldraw.com/_next/static/chunks/pages/_app-9edcb256d77d153e.js:18:47618
    at C (https://www.tldraw.com/_next/static/chunks/pages/_app-9edcb256d77d153e.js:18:47724)
    at e.batch (https://www.tldraw.com/_next/static/chunks/pages/_app-9edcb256d77d153e.js:18:227678)
    at n.r.batch (https://www.tldraw.com/_next/static/chunks/pages/_app-9edcb256d77d153e.js:18:294280)
    at https://www.tldraw.com/_next/static/chunks/pages/_app-9edcb256d77d153e.js:18:513235
    at https://www.tldraw.com/_next/static/chunks/main-ac48b75129494ec6.js:1:131768
    at Object.next (https://www.tldraw.com/_next/static/chunks/main-ac48b75129494ec6.js:1:131873)
    at n (https://www.tldraw.com/_next/static/chunks/main-ac48b75129494ec6.js:1:121840)
    at u (https://www.tldraw.com/_next/static/chunks/main-ac48b75129494ec6.js:1:122037)
    at https://www.tldraw.com/_next/static/chunks/main-ac48b75129494ec6.js:1:122096
    at new Promise (<anonymous>)
    at https://www.tldraw.com/_next/static/chunks/main-ac48b75129494ec6.js:1:121978
    at cj (https://www.tldraw.com/_next/static/chunks/pages/_app-9edcb256d77d153e.js:18:513738)
    at cA (https://www.tldraw.com/_next/static/chunks/pages/_app-9edcb256d77d153e.js:18:512419)
    at https://www.tldraw.com/_next/static/chunks/pages/_app-9edcb256d77d153e.js:24:183257
    at https://www.tldraw.com/_next/static/chunks/main-ac48b75129494ec6.js:1:131768
    at Object.next (https://www.tldraw.com/_next/static/chunks/main-ac48b75129494ec6.js:1:131873)
    at n (https://www.tldraw.com/_next/static/chunks/main-ac48b75129494ec6.js:1:121840)
    at u (https://www.tldraw.com/_next/static/chunks/main-ac48b75129494ec6.js:1:122037)
```

### How can we reproduce the bug?

[tldr.zip](https://github.com/tldraw/tldraw/files/12836983/tldr.zip)

Inside this project I try to draw anything or add a new image.

### What browsers are you seeing the problem on?

Chrome

### Contact Details

chris@mccormick.cx

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chr15m** [comment]
BTW maybe it's possible to ship sourcemaps and get a clearer link to the original code.

**Comment by MitjaBezensek** [comment]
Fixed here https://github.com/tldraw/tldraw/pull/2081
