### ISSUE TITLE
Validation error

### ISSUE THREAD

**Issue by ds300** [tldraw/tldraw#2166]
Maybe related to trackpad-pinch-zooming centering on wrong place?

```
ValidationError: At pointer(id = pointer:pointer).x: Expected a number, got NaN
    at Bu (https://staging.tldraw.com/assets/index-5d31d632.js:133:158)
    at wn.validationFn (https://staging.tldraw.com/assets/index-5d31d632.js:133:4137)
    at wn.validate (https://staging.tldraw.com/assets/index-5d31d632.js:133:565)
    at mE.validate (https://staging.tldraw.com/assets/index-5d31d632.js:131:22525)
    at Nv.validateRecord (https://staging.tldraw.com/assets/index-5d31d632.js:131:48452)
    at https://staging.tldraw.com/assets/index-5d31d632.js:131:38916
    at no (https://staging.tldraw.com/assets/index-5d31d632.js:131:5576)
    at gE.put (https://staging.tldraw.com/assets/index-5d31d632.js:131:38503)
    at we._updateInputsFromEvent (https://staging.tldraw.com/assets/index-5d31d632.js:150:4770)
    at https://staging.tldraw.com/assets/index-5d31d632.js:142:30407
    at https://staging.tldraw.com/assets/index-5d31d632.js:139:90389
    at qK (https://staging.tldraw.com/assets/index-5d31d632.js:131:5458)
    at no (https://staging.tldraw.com/assets/index-5d31d632.js:131:5580)
    at lJ.batch (https://staging.tldraw.com/assets/index-5d31d632.js:139:90320)
    at we.batch (https://staging.tldraw.com/assets/index-5d31d632.js:142:40349)
    at we.dispatch (https://staging.tldraw.com/assets/index-5d31d632.js:142:28060)
    at https://staging.tldraw.com/assets/index-5d31d632.js:297:96929
    at Object.eU (https://staging.tldraw.com/assets/index-5d31d632.js:56:9864)
    at nU (https://staging.tldraw.com/assets/index-5d31d632.js:56:10018)
    at rU (https://staging.tldraw.com/assets/index-5d31d632.js:56:10075)
    at _C (https://staging.tldraw.com/assets/index-5d31d632.js:56:31482)
    at vO (https://staging.tldraw.com/assets/index-5d31d632.js:56:31899)
    at https://staging.tldraw.com/assets/index-5d31d632.js:56:36812
    at zx (https://staging.tldraw.com/assets/index-5d31d632.js:59:36956)
    at zR (https://staging.tldraw.com/assets/index-5d31d632.js:56:8999)
    at tb (https://staging.tldraw.com/assets/index-5d31d632.js:56:33186)
    at gx (https://staging.tldraw.com/assets/index-5d31d632.js:56:17376)
    at wU (https://staging.tldraw.com/assets/index-5d31d632.js:56:17276)
    at HTMLDivElement.r (https://staging.tldraw.com/assets/index-5d31d632.js:36:1515)
```

**Comment by TodePond** [comment]
There seems to be something broken with one of the shapes on that board: 
```
ValidationError: At shape(id = shape:37r1dNsE1Ixn62rcWfSLP, type = draw).x: Expected a number, got NaN
    at Bu (https://staging.tldraw.com/assets/index-5d31d632.js:133:158)
    at wn.validationFn (https://staging.tldraw.com/assets/index-5d31d632.js:133:4137)
    at wn.validate (https://staging.tldraw.com/assets/index-5d31d632.js:133:565)
    at mE.validate (https://staging.tldraw.com/assets/index-5d31d632.js:131:22525)
    at Nv.validateRecord (https://staging.tldraw.com/assets/index-5d31d632.js:131:48452)
    at https://staging.tldraw.com/assets/index-5d31d632.js:131:38916
    at no (https://staging.tldraw.com/assets/index-5d31d632.js:131:5576)
    at gE.put (https://staging.tldraw.com/assets/index-5d31d632.js:131:38503)
    at Object.do (https://staging.tldraw.com/assets/index-5d31d632.js:142:25367)
    at https://staging.tldraw.com/assets/index-5d31d632.js:139:89849
    at https://staging.tldraw.com/assets/index-5d31d632.js:139:90701
    at no (https://staging.tldraw.com/assets/index-5d31d632.js:131:5576)
    at lJ.ignoringUpdates (https://staging.tldraw.com/assets/index-5d31d632.js:139:90694)
    at we.o [as _updateShapes] (https://staging.tldraw.com/assets/index-5d31d632.js:139:89821)
    at we.updateShapes (https://staging.tldraw.com/assets/index-5d31d632.js:142:86705)
    at https://staging.tldraw.com/assets/index-5d31d632.js:150:772
    at https://staging.tldraw.com/assets/index-5d31d632.js:139:90389
    at qK (https://staging.tldraw.com/assets/index-5d31d632.js:131:5458)
    at no (https://staging.tldraw.com/assets/index-5d31d632.js:131:5580)
    at lJ.batch (https://staging.tldraw.com/assets/index-5d31d632.js:139:90320)
    at we.batch (https://staging.tldraw.com/assets/index-5d31d632.js:142:40349)
    at we.putContentOntoCurrentPage (https://staging.tldraw.com/assets/index-5d31d632.js:150:34)
    at Kue (https://staging.tldraw.com/assets/index-5d31d632.js:218:34760)
    at _6 (https://staging.tldraw.com/assets/index-5d31d632.js:218:38809)
```

**Comment by TodePond** [comment]
Found the culprit!
