### ISSUE TITLE
[Bug]: TypeError createContext is not a function

### ISSUE THREAD

**Issue by navyblueyes** [tldraw/tldraw#2341]
### What happened?

Running NextJS and Tdraw. Successfully made a homepage with "home". Then I added <Tldraw> in the following fashion... 

```
"use client"

import { Tldraw } from "@tldraw/tldraw";

export default function Home() {
  return (
    <main className="h-screen w-screen">
      <Tldraw persistenceKey="snipdb" />
    </main>
  );
}
``` 
and I get the following error...
```
TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_1__.createContext) is not a function
    at eval (webpack-internal:///(rsc)/./node_modules/@radix-ui/react-dismissable-layer/dist/index.mjs:29:121)
    at (rsc)/./node_modules/@radix-ui/react-dismissable-layer/dist/index.mjs (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\.next\server\vendor-chunks\@radix-ui.js:892:1)
    at __webpack_require__ (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\.next\server\webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/@radix-ui/react-dialog/dist/index.mjs:29:92)
    at (rsc)/./node_modules/@radix-ui/react-dialog/dist/index.mjs (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\.next\server\vendor-chunks\@radix-ui.js:870:1)
    at __webpack_require__ (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\.next\server\webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/@tldraw/tldraw/dist-esm/lib/ui/components/primitives/Dialog.mjs:10:80)
    at (rsc)/./node_modules/@tldraw/tldraw/dist-esm/lib/ui/components/primitives/Dialog.mjs (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\.next\server\vendor-chunks\@tldraw.js:8230:1)
    at __webpack_require__ (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\.next\server\webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/@tldraw/tldraw/dist-esm/index.mjs:426:98)
    at (rsc)/./node_modules/@tldraw/tldraw/dist-esm/index.mjs (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\.next\server\vendor-chunks\@tldraw.js:6490:1)
    at __webpack_require__ (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\.next\server\webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./app/layout.tsx:10:72)
    at (rsc)/./app/layout.tsx (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\.next\server\app\page.js:184:1)
    at Function.__webpack_require__ (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\.next\server\webpack-runtime.js:33:43)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:540:9)
    at process.processTimers (node:internal/timers:514:7)
    at async ez (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:395720)  
    at async tt (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:399681)  
    at async tr (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:400231)  
    at async ti (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:404388)  
    at async C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:404907 {     
  digest: '1913056469'
}
TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_1__.createContext) is not a function
    at eval (webpack-internal:///(rsc)/./node_modules/@radix-ui/react-dismissable-layer/dist/index.mjs:29:121)
    at (rsc)/./node_modules/@radix-ui/react-dismissable-layer/dist/index.mjs (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\.next\server\vendor-chunks\@radix-ui.js:892:1)
    at __webpack_require__ (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\.next\server\webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/@radix-ui/react-dialog/dist/index.mjs:29:92)
    at (rsc)/./node_modules/@radix-ui/react-dialog/dist/index.mjs (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\.next\server\vendor-chunks\@radix-ui.js:870:1)
    at __webpack_require__ (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\.next\server\webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/@tldraw/tldraw/dist-esm/lib/ui/components/primitives/Dialog.mjs:10:80)
    at (rsc)/./node_modules/@tldraw/tldraw/dist-esm/lib/ui/components/primitives/Dialog.mjs (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\.next\server\vendor-chunks\@tldraw.js:8230:1)
    at __webpack_require__ (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\.next\server\webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/@tldraw/tldraw/dist-esm/index.mjs:426:98)
    at (rsc)/./node_modules/@tldraw/tldraw/dist-esm/index.mjs (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\.next\server\vendor-chunks\@tldraw.js:6490:1)
    at __webpack_require__ (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\.next\server\webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./app/layout.tsx:10:72)
    at (rsc)/./app/layout.tsx (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\.next\server\app\page.js:184:1)
    at Function.__webpack_require__ (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\.next\server\webpack-runtime.js:33:43)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:540:9)
    at process.processTimers (node:internal/timers:514:7)
    at async ez (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:395720)  
    at async tt (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:399681)  
    at async tr (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:400231)  
    at async ti (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:404388)  
    at async C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:404907 {     
  digest: '1913056469'
}
 ⨯ node_modules\@radix-ui\react-dismissable-layer\dist\index.mjs (23:89) @ eval
 ⨯ TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_1__.createContext) is not a function
    at __webpack_require__ (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\.next\server\webpack-runtime.js:33:43)
    at __webpack_require__ (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\.next\server\webpack-runtime.js:33:43)
    at __webpack_require__ (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\.next\server\webpack-runtime.js:33:43)
    at __webpack_require__ (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\.next\server\webpack-runtime.js:33:43)
    at eval (./app/layout.tsx:10:72)
    at (rsc)/./app/layout.tsx (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\.next\server\app\page.js:184:1)
    at Function.__webpack_require__ (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\.next\server\webpack-runtime.js:33:43)
null
 ⨯ node_modules\@radix-ui\react-dismissable-layer\dist\index.mjs (23:89) @ eval  
 ⨯ TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_1__.createContext) is not a function
    at __webpack_require__ (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\.next\server\webpack-runtime.js:33:43)
    at __webpack_require__ (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\.next\server\webpack-runtime.js:33:43)
    at __webpack_require__ (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\.next\server\webpack-runtime.js:33:43)
    at __webpack_require__ (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\.next\server\webpack-runtime.js:33:43)
    at eval (./app/layout.tsx:10:72)
    at (rsc)/./app/layout.tsx (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\.next\server\app\page.js:184:1)
    at Function.__webpack_require__ (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\.next\server\webpack-runtime.js:33:43)
null
 ⨯ node_modules\@radix-ui\react-dismissable-layer\dist\index.mjs (23:89) @ eval  
 ⨯ TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_1__.createContext) is not a function
    at __webpack_require__ (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\.next\server\webpack-runtime.js:33:43)
    at __webpack_require__ (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\.next\server\webpack-runtime.js:33:43)
    at __webpack_require__ (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\.next\server\webpack-runtime.js:33:43)
    at __webpack_require__ (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\.next\server\webpack-runtime.js:33:43)
    at eval (./app/layout.tsx:10:72)
    at (rsc)/./app/layout.tsx (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\.next\server\app\page.js:184:1)
    at Function.__webpack_require__ (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\.next\server\webpack-runtime.js:33:43)
digest: "853384284"
null
 ⨯ node_modules\@radix-ui\react-dismissable-layer\dist\index.mjs (23:89) @ eval  
 ⨯ TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_1__.createContext) is not a function
    at __webpack_require__ (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\.next\server\webpack-runtime.js:33:43)
    at __webpack_require__ (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\.next\server\webpack-runtime.js:33:43)
    at __webpack_require__ (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\.next\server\webpack-runtime.js:33:43)
    at __webpack_require__ (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\.next\server\webpack-runtime.js:33:43)
    at eval (./app/layout.tsx:10:72)
    at (rsc)/./app/layout.tsx (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\.next\server\app\page.js:184:1)
    at Function.__webpack_require__ (C:\Users\Micha\.LocalCode\Nextjs\NextJS40-1-snap\snap-site-start\.next\server\webpack-runtime.js:33:43)
digest: "1166296082"
null
 ⨯ node_modules\@radix-ui\react-dismissable-layer\dist\index.mjs (23:89) @ eval  
```

Note that I have used the "use client" as prescribed by NextJS and made adjustments to expand the <main>.

### How can we reproduce the bug?

Stock NextJS with TS.

Package.json is ...

```
{
  "name": "nextjs40-snap-site-start",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@tldraw/tldraw": "2.0.0-alpha.17",
    "ai": "2.2.24",
    "canvas-size": "1.2.6",
    "clsx": "2.0.0",
    "lucide-react": "0.292.0",
    "next": "14.0.1",
    "openai": "4.19.0",
    "prismjs": "1.29.0",
    "react": "18",
    "react-dom": "18",
    "react-hot-toast": "2.4.1"
  },
  "devDependencies": {
    "@types/canvas-size": "1.2.1",
    "@types/node": "20",
    "@types/prismjs": "1.26.3",
    "@types/react": "18",
    "@types/react-dom": "18",
    "autoprefixer": "10.0.1",
    "eslint": "8",
    "eslint-config-next": "14.0.1",
    "postcss": "8",
    "tailwindcss": "3.3.0",
    "typescript": "5"
  },
  "engines": {
    "node": ">=18.0.0"
  }
}

```

### Contact Details

mike.v.minkoff@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by steveruizok** [comment]
Hey, the tldraw component needs to be dynamically imported. Not sure if just marking a file as `use client` is enough for that: https://tldraw.dev/usage#Server-Rendering

**Comment by mdroidian** [comment]
@navyblueyes this worked for me

```typescript
"use client";

import dynamic from "next/dynamic";
import "@tldraw/tldraw/tldraw.css";

const Tldraw = dynamic(async () => (await import("@tldraw/tldraw")).Tldraw, {
  ssr: false,
});

export default function Home() {
  return (
    <div style={{ position: "fixed", inset: 0 }}>
      <Tldraw />
    </div>
  );
}
```

```json
  "dependencies": {
    "@tldraw/tldraw": "^2.0.0-alpha.19",
    "next": "14.0.4",
    "react": "^18",
    "react-dom": "^18",
  },
```

**Comment by steveruizok** [comment]
Excellent, thanks for sharing the solution @mdroidian !
