### ISSUE TITLE
Cmd+Z in VS Code causes error

### ISSUE THREAD

**Issue by wisinfun** [tldraw/tldraw#3641]
### What happened?

Using ⌘+Z in vscode will result in an error message
MacOS14.4.1 + vscode1.88.1

Error: cannot change atoms during reaction cycle
    at flushChanges (https://file+.vscode-resource.vscode-cdn.net/Users/ym/.vscode/extensions/tldraw-org.tldraw-vscode-2.0.31/editor//index.js:13708:13)
    at Transaction.commit (https://file+.vscode-resource.vscode-cdn.net/Users/ym/.vscode/extensions/tldraw-org.tldraw-vscode-2.0.31/editor//index.js:13669:9)
    at Transaction.abort (https://file+.vscode-resource.vscode-cdn.net/Users/ym/.vscode/extensions/tldraw-org.tldraw-vscode-2.0.31/editor//index.js:13690:12)
    at transaction (https://file+.vscode-resource.vscode-cdn.net/Users/ym/.vscode/extensions/tldraw-org.tldraw-vscode-2.0.31/editor//index.js:13758:11)
    at transact (https://file+.vscode-resource.vscode-cdn.net/Users/ym/.vscode/extensions/tldraw-org.tldraw-vscode-2.0.31/editor//index.js:13768:12)
    at HistoryManager.batch (https://file+.vscode-resource.vscode-cdn.net/Users/ym/.vscode/extensions/tldraw-org.tldraw-vscode-2.0.31/editor//index.js:29226:13)
    at Editor.exec [as _updateInstanceState] (https://file+.vscode-resource.vscode-cdn.net/Users/ym/.vscode/extensions/tldraw-org.tldraw-vscode-2.0.31/editor//index.js:29183:18)
    at Editor.updateInstanceState (https://file+.vscode-resource.vscode-cdn.net/Users/ym/.vscode/extensions/tldraw-org.tldraw-vscode-2.0.31/editor//index.js:33798:12)
    at SelectTool.cleanUpDuplicateProps (https://file+.vscode-resource.vscode-cdn.net/Users/ym/.vscode/extensions/tldraw-org.tldraw-vscode-2.0.31/editor//index.js:55638:21)
    at __EffectScheduler__.runEffect (https://file+.vscode-resource.vscode-cdn.net/Users/ym/.vscode/extensions/tldraw-org.tldraw-vscode-2.0.31/editor//index.js:55645:18)

### How can we reproduce the bug?

1. Create a new file
2. Draw a rectangle
3. Drag and copy rectangle by Option
4. Press ⌘+Z

### Contact Details

wisinfun@qq.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
Hey! We just published a new version. Could you try it out and let us know if you still see this issue?

**Comment by wisinfun** [comment]
> Hey! We just published a new version. Could you try it out and let us know if you still see this issue?

The problem has been resolved, thank you
