### ISSUE TITLE
[Bug]: Cannot read properties of undefined (reading 'top') in exportToBlob while trying to export text shapes

### ISSUE THREAD

**Issue by aspirin37** [tldraw/tldraw#3868]
### What happened?

Hello! I'm trying to implement a custom action in main menu that would return a png file that I could save and upload to our server. My current implementation looks like this: 

```
const saveAndClose = async () => {
      let shapeIds = editor.getCurrentPageShapeIds();
      const blob = await exportToBlob({ editor, ids: shapeIds, format: "png", name: 'some-filename'});
      const file = new File([blob], 'filename', { type: blob.type });
      return file;
 }
```

It works as expected and returns a file until I add any text shape to the editor - then it fails with an error:

```
TextManager.ts:148 Uncaught TypeError: Cannot read properties of undefined (reading 'top')
    at TextManager.measureElementTextNodeSpans (TextManager.ts:148:1)
    at TextManager.measureTextSpans (TextManager.ts:239:1)
    at SvgTextLabel (SvgTextLabel.tsx:59:1)
    at renderWithHooks (react-dom.development.js:15486:1)
    at mountIndeterminateComponent (react-dom.development.js:20103:1)
    at beginWork (react-dom.development.js:21626:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27490:1)
```
    
I also noticed that actions in main menu like 'export-all-as-png' use the same exportToBlob function but work perfectly even with text layers. I think the difference is that these actions use the editor instance from internal useEditor() function and I use an editor instance from onMount event, but I'm not sure about it. 

Is there a way to workaround this error or maybe just another way to save all the shapes as a blob without downloading the file?

### How can we reproduce the bug?

Just try to use the function above with the editor instance from onMount event while there are text shapes added

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aspirin37** [comment]
In case somebody would stuck with the same issue, I've managed to get the working version of the editor from useEditor according to the second part of this [documentation](https://tldraw.dev/examples/editor-api/api)

**Comment by kobe651jp** [comment]
I have the exact same problem.

Could you please share a sample code showing how you solved it?

Thank you.

**Comment by Kesavaraja** [comment]
Can you help me on how you solved this ? I am facing the same issue

**Comment by Kesavaraja** [comment]
@DeluxeOwl so this issue occurs when we use assetUrl in tldraw component. I faced this issue of getting error and multiple mount in tldraw because of asseturl. Just remove and try.

**Comment by c3ll256** [comment]
Still having the same issue

**Comment by c3ll256** [comment]
@Kesavaraja @DeluxeOwl If you are still having this issue, here's my solution, I override the TextShapeUtil's toSvg method in onMount like this:
```
    function findFont(name: TLDefaultFontStyle): FontFace | null {
      const fontFamily = DefaultFontFamilies[name]
      for (const font of document.fonts) {
        if (fontFamily.includes(font.family)) {
          return font
        }
      }
      return null
    }

    function getFontDefForExport(fontStyle: TLDefaultFontStyle): SvgExportDef {
      return {
        key: `${DefaultFontStyle.id}:${fontStyle}`,
        async getElement() {
          const font = findFont(fontStyle)
          if (!font) return null
    
          const url: string = (font as any).$$_url
          const fontFaceRule: string = (font as any).$$_fontface
          if (!url || !fontFaceRule) return null
    
          const fontFile = await (await fetch(url)).blob()
          const base64FontFile = await FileHelpers.blobToDataUrl(fontFile)
    
          const newFontFaceRule = fontFaceRule.replace(url, base64FontFile)
          return <style>{newFontFaceRule}</style>
        },
      }
    }

    // override the default TextShapeUtil toSVG method
    editor.getShapeUtil("text").toSvg = (shape: TLTextShape, ctx: SvgExportContext) => {
      if (shape.props.text) ctx.addExportDef(getFontDefForExport(shape.props.font))

      const bounds = editor.getShapeGeometry(shape).bounds
      const width = bounds.width / (shape.props.scale ?? 1)
      const height = bounds.height / (shape.props.scale ?? 1)
      const color = "white"
      
      // Calculate text positioning based on alignment
      let x = 0
      switch (shape.props.textAlign) {
        case 'middle':
          x = width / 2
          break
        case 'end':
          x = width
          break
        default: // 'start'
          x = 0
      }

      const FONT_SIZES: Record<TLDefaultSizeStyle, number> = {
        s: 18,
        m: 24,
        l: 36,
        xl: 44,
      }

      // Calculate vertical alignment (middle)
      const fontSize = FONT_SIZES[shape.props.size]
      const y = height / 2

      console.log(DefaultFontFamilies[shape.props.font])

      // Create text element with proper styling and positioning
      return (
        <text
          x={toDomPrecision(x)}
          y={toDomPrecision(y)}
          fontFamily={DefaultFontFamilies[shape.props.font]}
          fontSize={fontSize}
          fill={color}
          textAnchor={
            shape.props.textAlign === 'middle'
              ? 'middle'
              : shape.props.textAlign === 'end'
              ? 'end'
              : 'start'
          }
          dominantBaseline="central"
          style={{
            whiteSpace: 'pre-wrap',
            overflowWrap: 'break-word',
          }}
        >
          {shape.props.text.split('\n').map((line, i) => (
            <tspan
              key={i}
              x={toDomPrecision(x)}
              dy={i === 0 ? 0 : fontSize * 1.35}
            >
              {line}
            </tspan>
          ))}
        </text>
      )
    }
```
