### ISSUE TITLE
[Bug]: Failed to get webgl2 context

### ISSUE THREAD

**Issue by Dina-cell** [tldraw/tldraw#3925]
Hey, I ran into an error while using tldraw: Failed to get webgl2 context

Error: Failed to get webgl2 context
    at https://rendernet.ai/static/js/main.8ec39850.js:2:3439559
    at new dM (https://rendernet.ai/static/js/main.8ec39850.js:2:3442029)
    at https://rendernet.ai/static/js/main.8ec39850.js:2:3445798
    at il (https://rendernet.ai/static/js/main.8ec39850.js:2:2009982)
    at _c (https://rendernet.ai/static/js/main.8ec39850.js:2:2030209)
    at https://rendernet.ai/static/js/main.8ec39850.js:2:2028944
    at Cc (https://rendernet.ai/static/js/main.8ec39850.js:2:2029010)
    at cc (https://rendernet.ai/static/js/main.8ec39850.js:2:2022729)
    at Ui (https://rendernet.ai/static/js/main.8ec39850.js:2:1963122)
    at https://rendernet.ai/static/js/main.8ec39850.js:2:2029005

**Comment by MitjaBezensek** [comment]
Hey! What browser and version are you using? We are using webgl2 for rendering the minimap and it seems it like we somehow cannot create the webgl context.
