### ISSUE TITLE
[Bug]: Ungrouping shapes causes crash

### ISSUE THREAD

**Issue by elinx** [tldraw/tldraw#3932]
### What happened?

hit ctrl-d on a group of elements, then the program crash:
```
Error: aUV >= aUV
    at Cl (https://www.tldraw.com/assets/index-vZ7eszxo.js:105:4984)
    at Vi (https://www.tldraw.com/assets/index-vZ7eszxo.js:105:5489)
    at cf (https://www.tldraw.com/assets/index-vZ7eszxo.js:105:5900)
    at https://www.tldraw.com/assets/index-vZ7eszxo.js:138:65738
    at https://www.tldraw.com/assets/index-vZ7eszxo.js:139:9934
    at ja (https://www.tldraw.com/assets/index-vZ7eszxo.js:105:17746)
    at h1.extractingChanges (https://www.tldraw.com/assets/index-vZ7eszxo.js:118:29238)
    at https://www.tldraw.com/assets/index-vZ7eszxo.js:139:9656
    at eee.batch (https://www.tldraw.com/assets/index-vZ7eszxo.js:134:32740)
    at eee.ignore (https://www.tldraw.com/assets/index-vZ7eszxo.js:134:35581)
    at UI (https://www.tldraw.com/assets/index-vZ7eszxo.js:139:9628)
    at https://www.tldraw.com/assets/index-vZ7eszxo.js:138:65257
    at https://www.tldraw.com/assets/index-vZ7eszxo.js:134:32780
    at WG (https://www.tldraw.com/assets/index-vZ7eszxo.js:105:17571)
    at ja (https://www.tldraw.com/assets/index-vZ7eszxo.js:105:17750)
    at eee.batch (https://www.tldraw.com/assets/index-vZ7eszxo.js:134:32772)
    at re.duplicateShapes (https://www.tldraw.com/assets/index-vZ7eszxo.js:138:65015)
    at Object.onSelect (https://www.tldraw.com/assets/index-vZ7eszxo.js:329:7499)
    at Object.method (https://www.tldraw.com/assets/index-vZ7eszxo.js:357:50665)
    at rk (https://www.tldraw.com/assets/index-vZ7eszxo.js:357:46663)
    at ok (https://www.tldraw.com/assets/index-vZ7eszxo.js:357:47979)
    at HTMLBodyElement.p (https://www.tldraw.com/assets/index-vZ7eszxo.js:357:48785)
    at HTMLBodyElement.r (https://www.tldraw.com/assets/index-vZ7eszxo.js:89:2456)
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by SomeHats** [comment]
could you save your tldraw document as a file and share it with us?
