### ISSUE TITLE
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by cooper-del** [tldraw/tldraw#3960]
Hey, I ran into an error while using tldraw:

```js
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at fl (https://rendernet.ai/static/js/main.dde8fdc6.js:2:2011893)
    at pl (https://rendernet.ai/static/js/main.dde8fdc6.js:2:2011577)
    at fl (https://rendernet.ai/static/js/main.dde8fdc6.js:2:2012664)
    at ml (https://rendernet.ai/static/js/main.dde8fdc6.js:2:2013152)
    at vl (https://rendernet.ai/static/js/main.dde8fdc6.js:2:2013612)
    at ml (https://rendernet.ai/static/js/main.dde8fdc6.js:2:2013302)
    at vl (https://rendernet.ai/static/js/main.dde8fdc6.js:2:2013612)
    at ml (https://rendernet.ai/static/js/main.dde8fdc6.js:2:2013302)
    at vl (https://rendernet.ai/static/js/main.dde8fdc6.js:2:2013415)
    at ml (https://rendernet.ai/static/js/main.dde8fdc6.js:2:2013302)
```

My browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

**Comment by MitjaBezensek** [comment]
It's hard to say where exactly this is coming from. Maybe you can contact people at rendernet.ai? Then they can maybe reach out to use when they see when this is happening.

**Comment by steveruizok** [comment]
This happens in React when a node has been manually removed (i.e. `myContainerRef.current.remove()`). Later, when React tries to clean up a component, it can't find the element that it expects and throws an error as a result.

Chances are this is an implementation issue with rendernet, maybe a custom component or something in their UI.
