### ISSUE TITLE
[Bug]: Static assets serving is not working

### ISSUE THREAD

**Issue by aspirin37** [tldraw/tldraw#4366]
### What happened?

```
import {getAssetUrlsByImport} from '@tldraw/assets/imports.vite'
import {getAssetUrlsByMeta} from '@tldraw/assets/urls'
import { getAssetUrls } from '@tldraw/assets/selfHosted'

const assetUrls = getAssetUrls() / getAssetUrlsByImport() / getAssetUrlsByMeta()

<Tldraw assetUrls={assetUrls} />
```

These ways of serving static assets are not working with a regular vite config, the application isn't loading and I'm getting these errors:

`TypeError: Cannot read properties of undefined (reading 'startsWith')
    at formatAssetUrl (utils.js:16:21)
    at getAssetUrlsByImport (imports.vite.js:228:8)`
    
 
<img width="1162" alt="Screenshot 2024-08-07 at 11 59 02" src="https://github.com/user-attachments/assets/53b75370-cd4b-47ff-8e4d-135d3b695835">

<img width="988" alt="Screenshot 2024-08-07 at 12 05 39" src="https://github.com/user-attachments/assets/a73180bb-e06d-4d2b-b191-53130b18ec12">

### How can we reproduce the bug?

Just try to start a new project with react and vite and use one of these methods of serving static assets

### Where did this happen?

The developer package

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SomeHats** [comment]
Sorry about that - looks like vite has changed how some of this works, we should update the docs.

You now need to add `optimizeDeps: { exclude: ['@tldraw/assets'] }` to your vite config. Then the imports.vite option should work.
