### ISSUE TITLE
useSyncDemo causes assertion error

### ISSUE THREAD

**Issue by atomic-tang** [tldraw/tldraw#4393]
### What happened?

I've added tldraw sync into my project and tested the collaboration mode using the useSyncDemo hook like so:

```js
const Component = () => {
   const store = useSyncDemo({ roomId: 'example-room' });

   return (
      <div style={{ position: 'fixed', inset: 0 }}>
         <Tldraw store={store} />
      </div>
   );
}
```

But I am experiencing the following error:

```
Error: Assertion Error
    at Object.onMount (createTLStore.ts:121:1)
    at Tldraw.tsx:190:1
    at editor2.run.history (TldrawEditor.tsx:552:1)
    at transaction (transactions.ts:253:1)
    at transact (transactions.ts:284:1)
    at _HistoryManager.batch (HistoryManager.ts:102:1)
    at _Editor.run (Editor.ts:1068:1)
    at TldrawEditor.tsx:550:1
    at useEvent.tsx:42:1
    at TldrawEditor.tsx:562:1
    at commitHookEffectListMount (react-dom.development.js:23189:1)
    at commitLayoutEffectOnFiber (react-dom.development.js:23307:1)
    at commitLayoutMountEffects_complete (react-dom.development.js:24727:1)
    at commitLayoutEffects_begin (react-dom.development.js:24713:1)
    at commitLayoutEffects_begin (react-dom.development.js:24695:1)
    at commitLayoutEffects (react-dom.development.js:24651:1)
    at commitRootImpl (react-dom.development.js:26862:1)
    at commitRoot (react-dom.development.js:26721:1)
    at performSyncWorkOnRoot (react-dom.development.js:26156:1)
    at flushSyncCallbacks (react-dom.development.js:12042:1)
    at commitRootImpl (react-dom.development.js:26998:1)
    at commitRoot (react-dom.development.js:26721:1)
    at finishConcurrentRender (react-dom.development.js:26020:1)
    at performConcurrentWorkOnRoot (react-dom.development.js:25848:1)
    at workLoop (scheduler.development.js:266:1)
    at flushWork (scheduler.development.js:239:1)
    at performWorkUntilDeadline (scheduler.development.js:533:1)
    at run (setImmediate.js:40:1)
    at runIfPresent (setImmediate.js:69:1)
    at onGlobalMessage (setImmediate.js:109:1)
```

I looked up the code in my node_modules folder and the error is caused from the assert function in onMount
```ts
const store = new Store({
   id,
   schema,
   initialData,
   props: {
	defaultName,
	assets: {
		upload: assets.upload,
		resolve: assets.resolve ?? defaultAssetResolve,
	},
	onMount: (editor) => {
		assert(editor instanceof Editor) // this line is throwing an error in createTLStore.ts
		onMount?.(editor)
	},
	collaboration,
   },
})
```
My project has the following package:
Webpack 4.46.0
React loadable 15.6.4
Razzle 4.2.18
React 18.3.1
TLdraw 2.4.4
Tldraw Sync 2.4.4

But I am unable to produce this error in a Vite project using the same version of ReactJS. Any ideas why checking if the argument is an instance of Editor would return false?

```js
editor instanceof Editor // returns false
``` 

### Where did this happen?

The developer package

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atomic-tang** [comment]
It seems that the assert function is returning false because the editor in the onMount callback is constructed from the original Editor class and then being compared to the transpiled version of the Editor class. Is there another way to compare the object and class? Otherwise I may have to use patch-package.

**Comment by atomic-tang** [comment]
Assert passes if I change the line in createTLStore.ts from this:
```js
import { Editor } from '../editor/Editor.mjs'
```
to this:
```js
import { Editor } from "@tldraw/editor";
```
Should I create a pull request for this?

**Comment by ds300** [comment]
I don't think we'd want to merge that particular change since it's quite an unusual thing to do in a JS/TS code base, and the only reason to do it would be to work around a build issue in your particular app setup.

It should not be the case that you have multiple instantiations of interdependent modules talking to each other at runtime, that's simply gonna cause problems in any javascript code base and you should be fixing that at the root.

The only suggestion I can make for how to fix it would be to make sure you don't accidentally have multiple versions of tldraw in your package manager lockfile somehow. Otherwise, 🤷🏼 maybe updating webpack?

**Comment by atomic-tang** [comment]
Thanks, I've analysed my bundle and both the cjs and esm distributions were included. Forcing webpack to include just the cjs distribution did the trick.
