### ISSUE TITLE
Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by Kunaldw5** [tldraw/tldraw#4478]
Hey, I ran into an error while using tldraw:

```js
TypeError: Cannot read properties of undefined (reading 'name')
    at x (https://app.rendernet.ai/static/js/main.ec139712.js:2:542961)
    at Sa (https://app.rendernet.ai/static/js/main.ec139712.js:2:2339495)
    at Sl (https://app.rendernet.ai/static/js/main.ec139712.js:2:2396608)
    at xc (https://app.rendernet.ai/static/js/main.ec139712.js:2:2385714)
    at yc (https://app.rendernet.ai/static/js/main.ec139712.js:2:2385642)
    at vc (https://app.rendernet.ai/static/js/main.ec139712.js:2:2385505)
    at ac (https://app.rendernet.ai/static/js/main.ec139712.js:2:2382285)
    at cc (https://app.rendernet.ai/static/js/main.ec139712.js:2:2382676)
    at Ui (https://app.rendernet.ai/static/js/main.ec139712.js:2:2323216)
    at https://app.rendernet.ai/static/js/main.ec139712.js:2:2380218
```

My browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36

**Comment by ds300** [comment]
Hi! Thanks for the report!

I think we need a little more info to help diagnose this. An un-minified stack trace would be helpful. Or steps to reproduce.

**Comment by ds300** [comment]
Gonna close this now. Assuming it's no longer an issue. Feel free to open another issue if you're still having trouble.
