### ISSUE TITLE
[Bug]: core-js build error when running v3 with Vite

### ISSUE THREAD

**Issue by zacwood9** [tldraw/tldraw#4532]
### What happened?

After upgrading to tldraw v3, I am unable to run my Remix/Vite project, getting this error:

```
[vite] Error when evaluating SSR module /app/routes/_index.tsx: failed to import "tldraw"
|- file:///Users/zac/Developer/tlrepro/node_modules/@tldraw/editor/dist-esm/lib/exports/FontEmbedder.mjs:51
import { Promise as Promise2 } from "core-js";
         ^^^^^^^
SyntaxError: Named export 'Promise' not found. The requested module 'core-js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'core-js';
const { Promise: Promise2 } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:171:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:254:5)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:482:26)
    at async nodeImport (file:///Users/zac/Developer/tlrepro/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:52998:15)
    at async ssrImport (file:///Users/zac/Developer/tlrepro/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:52856:16)
    at async eval (/Users/zac/Developer/tlrepro/app/routes/_index.tsx:4:31)
    at async instantiateModule (file:///Users/zac/Developer/tlrepro/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:52914:5)
```

This is not an issue on the latest version of v2.

### How can we reproduce the bug?

Create a new Remix project:
```
bun create remix tldraw-core-js-repro
bun add tldraw
```

Add `<Tldraw />` to `app/routes/_index.ts`

Run `bun run dev`

Observe error

### Where did this happen?

The developer package

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zacwood9** [comment]
Confirmed fixed by 3.0.3. Thank you so much!!
