### ISSUE TITLE
Cannot read properties of undefined (reading 'point')

### ISSUE THREAD

**Issue by meetzaveri** [tldraw/tldraw#4667]
Hey, I ran into an error while using tldraw:

```js
TypeError: Cannot read properties of undefined (reading 'point')
    at https://www.tldraw.com/assets/index-CMILoHct.js:483:6769
    at Array.forEach (<anonymous>)
    at https://www.tldraw.com/assets/index-CMILoHct.js:483:4122
    at Array.forEach (<anonymous>)
    at https://www.tldraw.com/assets/index-CMILoHct.js:483:3739
    at cte (https://www.tldraw.com/assets/index-CMILoHct.js:119:15372)
    at Xo (https://www.tldraw.com/assets/index-CMILoHct.js:119:15551)
    at jie.batch (https://www.tldraw.com/assets/index-CMILoHct.js:151:16805)
    at le.run (https://www.tldraw.com/assets/index-CMILoHct.js:155:20268)
    at uwe (https://www.tldraw.com/assets/index-CMILoHct.js:483:2660)
    at se (https://www.tldraw.com/assets/root-C845Li4T.js:3:3704)
    at async https://www.tldraw.com/assets/root-C845Li4T.js:3:3936
```

My browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36

**Comment by GeorgVolkov** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
