### ISSUE TITLE
af8ha >= aeazh

### ISSUE THREAD

**Issue by wasaga** [tldraw/tldraw#5012]
Hey, I ran into an error while using tldraw:

tried to duplicate an arrow. 

```js
Error: af8ha >= aeazh
    at ute (https://www.tldraw.com/assets/index-RyNgJpkT.js:124:9426)
    at HF (https://www.tldraw.com/assets/index-RyNgJpkT.js:124:9498)
    at dte (https://www.tldraw.com/assets/index-RyNgJpkT.js:124:9662)
    at WF (https://www.tldraw.com/assets/index-RyNgJpkT.js:124:9583)
    at op (https://www.tldraw.com/assets/index-RyNgJpkT.js:124:10153)
    at https://www.tldraw.com/assets/index-RyNgJpkT.js:162:62630
    at Array.forEach (<anonymous>)
    at https://www.tldraw.com/assets/index-RyNgJpkT.js:162:62479
    at Ele (https://www.tldraw.com/assets/index-RyNgJpkT.js:126:11917)
    at oi (https://www.tldraw.com/assets/index-RyNgJpkT.js:126:12096)
    at Khe.batch (https://www.tldraw.com/assets/index-RyNgJpkT.js:158:17990)
    at _e.run (https://www.tldraw.com/assets/index-RyNgJpkT.js:162:20922)
    at _e.duplicateShapes (https://www.tldraw.com/assets/index-RyNgJpkT.js:162:61687)
    at Object.onSelect (https://www.tldraw.com/assets/index-RyNgJpkT.js:398:8503)
    at Object.method (https://www.tldraw.com/assets/index-RyNgJpkT.js:473:57079)
    at zO (https://www.tldraw.com/assets/index-RyNgJpkT.js:473:53075)
    at HO (https://www.tldraw.com/assets/index-RyNgJpkT.js:473:54391)
    at HTMLBodyElement.p (https://www.tldraw.com/assets/index-RyNgJpkT.js:473:55197)
    at HTMLBodyElement.r (https://www.tldraw.com/assets/index-RyNgJpkT.js:90:2707)
```

My browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36

**Comment by steveruizok** [comment]
Thanks @wasaga. I've run into this too, though it's hard to find where the problem is. Was this on a shared room / multi-user project, or something you'd only worked on alone?
