### ISSUE TITLE
[bug] Export to PNG, JPG and WEBP create empty files

### ISSUE THREAD

**Issue by Brifien** [tldraw/tldraw#520]
Export to PNG, JPG and WEBP create empty files.
I tried with Firefox and Chrome, even with very simple drawing.
SVG and JSON are working.

**Comment by ppalone** [comment]
I checked the console while exporting, it makes request to the `https://www.tldraw.com/api/export` and the request fails with 500 status.

**Comment by steveruizok** [comment]
Here's the error message from the server:

```
[POST] /api/export
09:13:31:58
2022-01-18T09:13:32.295Z	ce7514ae-92a5-42bf-b7cc-2e4535c745ea	ERROR	Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (938248).
2022-01-18T09:13:32.300Z	ce7514ae-92a5-42bf-b7cc-2e4535c745ea	ERROR	TypeError: Cannot read property 'close' of null
    at handler (/var/task/apps/www/.next/server/pages/api/export.js:208:19)
    at async Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils.js:102:9)
    at async Server.handleApiRequest (/var/task/node_modules/next/dist/server/next-server.js:1064:9)
    at async Object.fn (/var/task/node_modules/next/dist/server/next-server.js:951:37)
    at async Router.execute (/var/task/node_modules/next/dist/server/router.js:222:32)
    at async Server.run (/var/task/node_modules/next/dist/server/next-server.js:1135:29)
    at async Server.handleRequest (/var/task/node_modules/next/dist/server/next-server.js:325:20)
    at async Server.<anonymous> (/var/task/___next_launcher.js:32:9)
2022-01-18T09:13:32.300Z	ce7514ae-92a5-42bf-b7cc-2e4535c745ea	ERROR	TypeError: Cannot read property 'close' of null
    at handler (/var/task/apps/www/.next/server/pages/api/export.js:208:19)
    at async Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils.js:102:9)
    at async Server.handleApiRequest (/var/task/node_modules/next/dist/server/next-server.js:1064:9)
    at async Object.fn (/var/task/node_modules/next/dist/server/next-server.js:951:37)
    at async Router.execute (/var/task/node_modules/next/dist/server/router.js:222:32)
    at async Server.run (/var/task/node_modules/next/dist/server/next-server.js:1135:29)
    at async Server.handleRequest (/var/task/node_modules/next/dist/server/next-server.js:325:20)
    at async Server.<anonymous> (/var/task/___next_launcher.js:32:9)
RequestId: ce7514ae-92a5-42bf-b7cc-2e4535c745ea Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

**Comment by steveruizok** [comment]
The `puppeteer` package was mistakenly added to `@tldraw/tldraw` rather than `@tldraw/www`. Let's see if fixing that fixes this.

**Comment by ppalone** [comment]
https://tldraw.com gives me same error, I assume changes aren't deployed yet.
https://tldraw-tldraw.vercel.app & https://tldraw-git-main-tldraw.vercel.app gives CORS error 'Access-Control-Allow-Origin' missing while exporting.

**Comment by ppalone** [comment]
Export works like charm now, issue can be closed.

**Comment by steveruizok** [comment]
Should be working now! Thanks for bringing it up @Brifien  @ppalone

**Comment by Aienao** [comment]
> 

hey,can you tell me how to deploy to vercel?thanks!
